name: crossfit
favicon: null
layout_spectrum: 0.87614
typography_spectrum: 0.73414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020304'
    - '#dedede'
    - '#e14139'
    - '#57585c'
    - '#a19996'
  brandStrength: 1
  lightness: 0.8272129620891064
  saturation: 0.8396026885602623
  rhythmicContrast: 0.2343045079614967
purpose: []
