name: crossfit
favicon: null
layout_spectrum: 0.5312457368709147
typography_spectrum: 0.5299023180268705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8640442579053342
  lightness: 0.8272129620891064
  saturation: 0.8396026885602623
  rhythmicContrast: 0.2343045079614967
purpose: []
