name: crossfit
favicon: null
layout_spectrum: 0.50048
typography_spectrum: 0.6565
title: crossfit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5061231-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#7f7e79'
    - '#455761'
    - '#ded1ce'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
