name: crossfit
favicon: null
layout_spectrum: 0.37744
typography_spectrum: 0.6565
title: crossfit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5061231-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020304'
    - '#dedede'
    - '#e14139'
    - '#57585c'
    - '#a19996'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
