name: crossfit
favicon: null
layout_spectrum: 0.50048
typography_spectrum: 0.6565
title: crossfit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5061231-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#e24139'
    - '#eda8a0'
    - '#30e6cf'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
